### ISSUE TITLE
running hlint when installed using --copy-compiler-bins

### ISSUE THREAD

**Issue by ndwarshuis** [flycheck/flycheck-haskell#116]
For projects where I want to run a specific version of hlint, is it currently possible for flycheck to find the hlint binary in the compiler-tools directory for a specific ghc version?

To be concrete, if I installed hlint from my project root (which specifies ghc 9.2.5) via:

```
stack build --copy-compiler-tool hlint
```

hlint is installed in `/home/me/.local/share/stack/compiler-tools/x86_64-linux-tinfo6/ghc-9.2.5/bin/hlint`, but flycheck does not seem to find it as the hlint checker will remain disabled if I open any .hs file in the project where this is installed.

I could just `stack install hlint` globally like pretty much all guides seem to suggest, but this doesn't seem like a good best practice for reproducible environments in general.

**Comment by sergv** [comment]
I should make a discraimer that the `flycheck-haskell` project doesn't deal with hlint, it only concerns itself with getting proper parameters for `ghc` in order to run successful compilation-like checks. Your question really belongs to the main flycheck repository https://github.com/flycheck/flycheck since that's where the `hlint` checker is defined.

However your concerns with executable location can be addressed with flycheck's own options. Namely either `flycheck-command-wrapper-function` from https://github.com/flycheck/flycheck/blob/master/flycheck.el#L475 or `flycheck-executable-find`  from https://github.com/flycheck/flycheck/blob/master/flycheck.el#L493 can be used to resolve `hlint` executable location.

**Comment by ndwarshuis** [comment]
@sergv thanks, overriding `flycheck-executable-find` was simple enough.

And I would agree with your disclaimer, my first impression of `flycheck-haskell` was that it configures flycheck in a stack/cabal-aware manner (which would include being aware of `compiler-tools` if it were true in the broadest sense, which apparently it is not).
