### ISSUE TITLE
flycheck-haskell-configure won't be called if `enable-local-variables` is nil

### ISSUE THREAD

**Issue by Enzo-Liu** [flycheck/flycheck-haskell#40]
After configure
``` emacs-lisp
(eval-after-load 'flycheck
  '(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup))
```

I notice `cabal sandbox config` takes no effect for `flycheck-haskell`. Manually call `flycheck-haskell-configure` will fix this problem.

Looking into the `flycheck-haskell-setup`  and [hack-local-variables-hook](http://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html)
``` emacs-lisp
 (add-hook 'hack-local-variables-hook #'flycheck-haskell-configure)
```
I found with `enable-local-variables` set to nil, the `hack-local-variables-hook` will never be called.

Add check for this?

**Comment by lunaryorn** [comment]
@Enzo-Liu There are no checks for that, and I think it won't be easy to work around this.  Why do you set `enable-local-variables` to `nil`?

**Comment by Enzo-Liu** [comment]
When I saw prompt for  apply variables, it feels a little annoying... 
So I set `enable-local-variables` to `nil`.
Now I use 
``` emacs-lisp
(setf enable-local-variables :safe)
```
And everything is fine.

But maybe could do something in `flycheck-haskell-setup` like this?:
``` emacs-lisp
(if enable-local-variables
    (add-hook 'hack-local-variables-hook #'flycheck-haskell-configure)
    (flycheck-haskell-configure)))
```

**Comment by lunaryorn** [comment]
@Enzo-Liu Are you aware that you can type `!` in this prompt to permanently accept all variables therein as safe for the current and any future Emacs session?  I use it all the time.

I'd strongly recommend against disabling local variables, because these are _the_ standard way of project-local settings in Emacs.  As such, I don't think it's worth the effort to support them.

The  purpose of adding to `hack-local-variables-hook` is to make sure that any kind of user settings never overwrite the settings from Flycheck Haskell, because that hook is the very last that runs for a major mode.  Specifically, a user can safely put stuff in any kind of mode hook without interfering with Flycheck Haskell.
