### ISSUE TITLE
Don't require stack

### ISSUE THREAD

**Issue by ivan-m** [flycheck/flycheck-haskell#49]
Would it please be possible to make stack usage optional?

Whilst I have stack installed (and hence the default for `flycheck-haskell-runghc-command` uses it), I'm not actually using it for my day-to-day development.  As such, I frequently get spurious errors because stack doesn't know about a module since I installed it using `cabal` sandboxes.

**Comment by lunaryorn** [comment]
I'm not sure what your problem is.  Why can't you just customise the option and disable the `haskell-stack-ghc` checker?

**Comment by lunaryorn** [comment]
@ivan-m Is this still an issue?  Did you try to customise the option and disable `haskell-stack-ghc`?

**Comment by ivan-m** [comment]
Sorry, I mis-spoke and this isn't the problem with the `haskell-stack-ghc` checker.

However, I do find the usage of `stack` by the [`flycheck-haskell-runghc-command`](https://github.com/flycheck/flycheck-haskell/blob/master/flycheck-haskell.el#L75) curious: just because I happen to have it installed doesn't mean I necessarily want it used (though I'm semi-guessing that it's used to automatically install any dependencies that might be needed).

**Comment by lunaryorn** [comment]
With all due respect, please do not guess. `flycheck-haskell-runghc-command` is not used for syntax checking.  

It's only purpose is to provide a Haskell interpreter to run the built-in Haskell helpers of this package to parse the Cabal configuration file.  We default to `stack` because most stack users don't have a global GHC installation anymore—it's simply the safest choice to get a working Haskell interpreter.

You can still use Cabal sandboxes regardless of this option, though.  In fact, Flycheck Haskell will locate and configure a Cabal sandbox even if  `flycheck-haskell-runghc-command` points to `stack`.

Consider `flycheck-haskell-runghc-command` as a purely technical detail to obtain a Haskell interpreter to run some internal code.  It has no effect on syntax checking at all.  I understand though that it's probably not a perfect choice for everyone, but that's why the option is customisable.

I'm closing this issue.

**Comment by ivan-m** [comment]
In my follow-up I didn't mention syntax checking.  I was just questioning the usage of `stack` rather than just plain `runghc`.

(And I question how accurate your statement of "most stack users don't have a global GHC installation anymore", as well as the "safest choice" aspect.)

**Comment by lunaryorn** [comment]
@ivan-m What concrete problems does `stack` cause for you?  And why can't you just change the option to use `runghc`?

I do not know how accurate that statement is.  I don't doubt that it's somewhat inaccurate and only a poor reflection of the variety of Haskell setups to be found in the Haskell community as it's obviously just based on my somewhat limited personal experience.   Still, that experience was the best I had when making the choice for a default.

I'm sure that your experience is quite different from mine, and I'm sorry that the current choice does not work great.  I'm happy to change the default if you have _concrete_ issues and problems with the current default and if you can suggest a better default to use instead that will work for a greater part of our user base.

**Comment by ivan-m** [comment]
I haven't had an issue with it, was just curious at the choice (I had had a problem with the `haskell-stack-ghc` checker which I had accidentally conflated when I first posted it due to the project name, hence the poor word choice).
