### ISSUE TITLE
haskell-cabal-get-setting no longer exists

### ISSUE THREAD

**Issue by tranma** [flycheck/flycheck-haskell#54]
This function is used in `flycheck-haskell-get-config-value`, it no longer exists in the latest release of haskell-mode.

**Comment by reuleaux** [comment]
just for the record: haskell-cabal-get-setting was renamed to haskell-cabal--get-field,
according to the history of haskell-cabal.el in haskell-mode, cf.:
  https://github.com/haskell/haskell-mode/commit/bd17a1611fbc02ff55d333c1ec73efedfaff5668#diff-6e1a8a553b50ac9e0ff64fff4133a1c5
so for me a temporary workaround was to use:

  (defalias 'haskell-cabal-get-setting 'haskell-cabal--get-field)

but of course it would be nice, if this was fixed properly here in flycheck-haskell.

**Comment by lunaryorn** [comment]
Please feel welcome to provide a patch and open a pull request.  I do not have time to fix this currently.

/cc @gracjan

**Comment by geraldus** [comment]
@gracjan :D Ahh, I foreseen that.  Would it be better to return `haskell-cabal-get-setting` and mark it as obsolete?

**Comment by lunaryorn** [comment]
@geraldus Best would be to provide us with a proper API to get Cabal settings.  I'd not like to have to use an internal function for our purposes.  :relaxed:

**Comment by geraldus** [comment]
@lunaryorn I agree, also I see that current implementation have some drawbacks.  I would like I have more time, there are a lot of things to do with haskell-mode.

**Comment by gracjan** [comment]
@geraldus: Lets provide obsolete alias for now.

**Comment by lunaryorn** [comment]
@gracjan I've changed the code to use `haskell-cabal--get-field` to fix the warning.

I'm not too happy about using a function that's marked as internal, and I hope it doesn't just go away at some point.  I'd prefer, though, if we had a proper function like `haskell-cabal-get-field-from-buffer` or so, with a bit more guarantees.

Closing.

**Comment by gracjan** [comment]
Great, thanks.

Note that the whole `haskell-cabal` module was created when `.cabal` files were flat structures of key-value pairs. Since then cabal got to understand multiple executable, library, test and benchmark sections. The structure isn't flat anymore and therefore would require new abstraction. There was an attempt at that and we still have leftovers in haskell mode.

So cabal support is a mess, and I do not see us fixing this soon because of lack of resources.

**Comment by lunaryorn** [comment]
@gracjan We do not parse `.cabal` with Emacs Lisp; we only use this function to parse Cabal configuration files (sandbox and global) to extract the package DB paths and the compiler setting.

I'm not sure whether we're going to keep this for long (because Stack), and it's not a big deal, so if you're going to drop the whole Cabal stuff from Haskell Mode we can just copy the relevant pieces.  Just tell us so that we don't forget :)

**Comment by geraldus** [comment]
@lunaryorn hi!  I agree this function should exist.  There is a caveat however.  We can provide such function right now, but current implementation of `haskell-cabal--get-field` is very raw, it does not take into account possibility of fields duplication and conditional flags, we lack proper structure to present cabal file.  As for API, I think we should provide some API layer as separate module.
