### ISSUE TITLE
Prelude.hs breaks `flycheck-haskell-read-cabal-configuration`

### ISSUE THREAD

**Issue by korayal** [flycheck/flycheck-haskell#70]
I'm using Intero in Spacemacs, and when I have a file named `Prelude.hs` at the same folder with the file I'm currently working on, I get the error below:

```
Reading Haskell configuration failed with exit code 1 and output:

<interactive>:1:1: error:
    attempting to use module ‘Prelude’ (./Prelude.hs) which is not loaded
```
And when I looked into the command that's being executed, it was as below:

```
stack --verbosity silent runghc --no-ghc-package-path -- /home/korayal/.emacs.d/elpa/flycheck-haskell-20170604.447/get-cabal-configuration.hs /home/korayal/Workspace/test-project/test-project.cabal
```
I tried the same command at the project root and it executed alright. But when I tried to execute the same command at the path where the file is located, I got the same error. 

Which (I guess) means the command is not being executed at the project root. Is this the normal behavior?

**Comment by sergv** [comment]
@korayal Thanks for reporting the issue! Indeed, `flycheck-haskell` does not change `default-directory` when it gets configuration from the cabal file. That is, it uses `default-directory` of the buffer as the working directory for the execution of `get-cabal-configuration.hs`. Since this module uses Prelude (which is hardly surprising) the `runghc` tries to look for module named `Prelude` in its search path. By default this search path includes `.`, so if buffers' `default-directory` happens to have module named `Prelude` then `runghc` will try to use it and fail.

I think the best solution for this problem is to reset default search path to nothing via `-i` ghc flag (according to the [docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/separate_compilation.html#search-path)), so that modules in the current directory will not interfere with `runghc` execution. Another possible solution could be to change `default-directory` variable during call to `runghc` to point to the root of the project. However, this will still fail if projects' root contains `Prelude` module! Even though it's uncommon, it's probably best to handle this case too. I'll make a PR that adds `-i` flag.

**Comment by sergv** [comment]
@korayal It should be fixed now.
